### ISSUE TITLE
Radio buttons too small

### ISSUE THREAD

**Issue by kamicut** [kamicut/vote-here-2016#3]
Reported by user: Radio buttons too small on Firefox/Android Marshmallow

**Comment by chaficnajjar** [comment]
One thing we could do is use "label" elements with [the "for" attribute](http://stackoverflow.com/a/18432439/1300992) to allow the user to click on the label which will be treated like clicking on the associated radio button.

**Comment by kamicut** [comment]
Stale. Let me know if you have ideas or want this re-opened.
