### ISSUE TITLE
Horizontally and vertically center the "Where do I vote?" window.

### ISSUE THREAD

**Issue by chaficnajjar** [kamicut/vote-here-2016#5]
I think it's preferable to have the "Where do I vote?" window horizontally and vertically centered, on desktop, tablet and mobile. What do you think?

Additionally, it's not possible to pan the map when the cursor is on either side of the window. Panning only works when the cursor is below the window (or above the window, in the tiny space). This issue will be fixed if I horizontally and vertically center the window.

**Comment by kamicut** [comment]
I agree, it's a good idea @chaficnajjar. What do you propose for vertical centering?

**Comment by kamicut** [comment]
Stale. Let me know if you have ideas or want this re-opened.
