### ISSUE TITLE
Sometimes the marker will appear behind the main text box

### ISSUE THREAD

**Issue by saeidw** [kamicut/vote-here-2016#6]
In the screenshot the marker is behind the text box that contains directions to the polling station.

![sawwet2016-1](https://cloud.githubusercontent.com/assets/227545/15093694/db0acb60-1497-11e6-99cf-c1022ab16581.png)

Maybe decreasing the opacity of the text box can help make the marker more visible in such cases, or having the map somehow be separate from the text?

**Comment by kamicut** [comment]
Oh wow, yeah. One quick fix could be to not have so much whitespace in the location and make it one long string instead of three lines. I could also remove the about text when a location is found. What do you think @saeidw ?

**Comment by saeidw** [comment]
Having the about text accessible but out of the way might be a nice fix. The information is useful to have but it can be moved somewhere else.

**Comment by kamicut** [comment]
Stale. Let me know if you have ideas or want this re-opened.
